function my_figure(opisX, opisY, tytul)
%% Zmienione argumenty wejściowe funkcji na opisy osi!
  
%% CREATEFIGURE2(X1, Y1) <-- Taka była pierwotna składnia funkcji.
%  X1:  vector of x data
%  Y1:  vector of y data
  
%  Auto-generated by MATLAB on 18-Mar-2020 10:38:53
  
% Create figure
% figure1 = figure; % To usuwamy, gdyż rysunek będzie tworzony 
                    % na zewnątrz funkcji
  
% Create axes
% axes1 = axes;     % To również usuwamy, gdyż obiekt axes, jest już
                    % stworzony na aktywnym rysunku
axes1 = gca;
hold(axes1,'on');
  
% Create plot
% plot(X1,Y1,'LineWidth',2);    % To samo dotyczy linii
  
% Create ylabel
% ylabel({'Opis osi Y'});       % Podmieniamy, tak aby móc wprowadzać
ylabel(opisY);                  % swój tekst. Podobnie z xlabel i title
  
% Create xlabel
xlabel(opisX);
  
% Create title
title(tytul);
  
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Century Gothic','FontSize',12,...
    'LabelFontSizeMultiplier',1.3,'TitleFontSizeMultiplier',1.1,'XGrid','on',...
    'LineWidth',1,'TickLength',[0.02 0.025],'XMinorTick','on','YGrid','on','YMinorTick','on');
  
%% Jeżeli rysunek zawiera więcej niż jedną linia, konieczna jest pętla:
  
% liczba_lini = size(axes1.Children);
% for k = 1 : liczba_lini
%     axes1.Children(k,1).LineWidth = 2;
% end